-- ============================================================
-- BAA OS — Section G1 — Database Schema
-- File: db/schema.sql
--
-- STATUS: SCHEMA / MIGRATION DESIGN ONLY. No live database is
-- connected to this project. Nothing in this repo executes this
-- file against a real database. See SCHEMA.md for full docs and
-- MIGRATION-MAPPING.md for how existing localStorage data will
-- eventually map onto these tables (actual migration = G5).
--
-- Target dialect: PostgreSQL (chosen for wide Vercel-compatible
-- managed-Postgres support — e.g. Neon, Supabase, Vercel Postgres —
-- all reachable over HTTP/serverless drivers from Edge Functions,
-- which matches this project's existing Vercel Edge architecture).
-- See SCHEMA.md section 20 for the reasoning and what G4 still has
-- to decide (which driver/client).
--
-- Conventions used throughout:
--   * Primary keys are TEXT ids in the app's own uid() format
--     (e.g. 'learner_...', 'attempt_...') so IDs generated by the
--     existing client-side code (js/*.js `uid()`) remain valid
--     unchanged if/when they are written to the database. See
--     SCHEMA.md section 16 for the identifier strategy.
--   * created_at / updated_at are set by the application layer
--     (data-access repositories), not by DB triggers, so that the
--     LocalStorageAdapter and DatabaseAdapter behave identically.
--   * Nothing here is executed by this codebase yet (G1 = design
--     only). A future migration tool (G5) is expected to apply this
--     file against a real provisioned database.
-- ============================================================


-- ============================================================
-- 1. IDENTITY / RELATIONSHIPS
--    (schema only — G1 does not implement auth/authorization;
--    see G2/G3. These tables exist so every other table has a
--    stable place to eventually attach a real account.)
-- ============================================================

CREATE TABLE users (
  id            TEXT PRIMARY KEY,          -- e.g. 'user_...'
  display_name  TEXT NOT NULL,
  email         TEXT UNIQUE,               -- nullable: G1 does not require an account to exist
  created_at    TIMESTAMPTZ NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL,
  deactivated_at TIMESTAMPTZ                -- soft-delete / lifecycle, see SCHEMA.md section 18
);

-- A user can hold more than one role (e.g. a teacher who is also a parent).
CREATE TABLE user_roles (
  user_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role     TEXT NOT NULL CHECK (role IN ('student', 'parent', 'teacher', 'admin')),
  granted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, role)
);


-- ============================================================
-- 1a. AUTHENTICATION (Section G2.1 — SCHEMA / DESIGN ONLY)
--    G1 defined `users` and `user_roles` as identity foundations
--    but deliberately implemented no authentication (see G1's
--    "what G1 does not do", and SCHEMA.md section 14). G1 also
--    never defined how a user's credential or a login session
--    would be stored — `credentials` and `auth_sessions` below
--    fill that specific, previously-undefined gap.
--
--    STATUS: exactly like every other table in this file, these
--    two tables are SCHEMA / MIGRATION DESIGN ONLY. No live
--    database is connected to this project (see file header).
--    Nothing in this codebase creates, reads, or writes to these
--    tables yet — no signup form, no login form, no session
--    issuance/verification code, no password hashing call. That
--    is out of scope for G2.1 and belongs to later G2 checkpoints
--    (client-side account creation/login, session-aware
--    repository wiring) and, for anything requiring a real,
--    network-verified secret, to G4 (secure API layer / backend
--    migration — see SCHEMA.md section 12, which explains why no
--    live database or provider exists yet).
-- ============================================================

-- One row per user's login credential. Only a password HASH is ever
-- stored — never a plaintext password (requirement carried over from
-- G1's privacy stance in SCHEMA.md section 9, applied here to auth
-- data). `algorithm` is recorded per-row so a future hashing-scheme
-- upgrade doesn't require guessing what produced an existing hash.
-- A user has at most one row here today (1:1 with `users`); modeled
-- as its own table rather than columns on `users` so `users` stays
-- a plain identity table and credential rotation/history can be
-- extended later without touching the identity schema G1 already
-- shipped.
CREATE TABLE credentials (
  user_id        TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  password_hash  TEXT NOT NULL,
  algorithm      TEXT NOT NULL DEFAULT 'argon2id', -- hashing scheme identifier, not chosen/implemented by G2.1
  created_at     TIMESTAMPTZ NOT NULL,
  updated_at     TIMESTAMPTZ NOT NULL
);

-- One row per active (or expired/revoked) login session. Sessions
-- are modeled as their own table, not a JWT-only/stateless scheme,
-- so a session can be looked up, listed, and revoked server-side —
-- matching this project's existing "never silently fabricate or
-- lose state" stance (see G1's soft-delete/lifecycle approach,
-- SCHEMA.md section 10). `token_hash` stores a hash of the session
-- token, never the raw token, mirroring the credentials table's
-- hash-only rule. `revoked_at` follows the same soft-delete pattern
-- G1 already uses elsewhere (`deactivated_at`, `archived_at`, etc.)
-- rather than deleting session rows outright.
CREATE TABLE auth_sessions (
  id            TEXT PRIMARY KEY,          -- e.g. 'session_...'
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash    TEXT NOT NULL UNIQUE,
  created_at    TIMESTAMPTZ NOT NULL,
  expires_at    TIMESTAMPTZ NOT NULL,
  revoked_at    TIMESTAMPTZ
);
CREATE INDEX idx_auth_sessions_user ON auth_sessions(user_id);


-- A learner is the "student" identity that owns learning data. It is
-- modeled separately from `users` because Section A/B/C/D currently
-- identify a student purely by a display name in localStorage, with
-- no account at all — a learner record must be able to exist before
-- (or without) a login. `user_id` is nullable and is filled in once
-- G2 (auth) links a real account to the learner.
CREATE TABLE learners (
  id            TEXT PRIMARY KEY,          -- e.g. 'learner_...'
  user_id       TEXT REFERENCES users(id) ON DELETE SET NULL,
  display_name  TEXT NOT NULL,             -- maps to today's `baa_student_name`
  created_at    TIMESTAMPTZ NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL,
  deactivated_at TIMESTAMPTZ
);

CREATE TABLE parent_learner (
  id            TEXT PRIMARY KEY,
  parent_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  learner_id    TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  relationship  TEXT NOT NULL DEFAULT 'parent', -- 'parent' | 'guardian' | 'other_authorized_adult'
  status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  created_at    TIMESTAMPTZ NOT NULL,
  revoked_at    TIMESTAMPTZ,
  UNIQUE (parent_user_id, learner_id)
);

CREATE TABLE teacher_learner (
  id            TEXT PRIMARY KEY,
  teacher_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  learner_id    TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  created_at    TIMESTAMPTZ NOT NULL,
  revoked_at    TIMESTAMPTZ,
  UNIQUE (teacher_user_id, learner_id)
);

CREATE TABLE classes (
  id            TEXT PRIMARY KEY,
  teacher_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  subject       TEXT,
  created_at    TIMESTAMPTZ NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL,
  archived_at   TIMESTAMPTZ
);

CREATE TABLE class_members (
  id            TEXT PRIMARY KEY,
  class_id      TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  learner_id    TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'removed')),
  joined_at     TIMESTAMPTZ NOT NULL,
  removed_at    TIMESTAMPTZ,
  UNIQUE (class_id, learner_id)
);


-- ============================================================
-- 2. LEARNING PROFILE
-- ============================================================

CREATE TABLE learning_profiles (
  learner_id    TEXT PRIMARY KEY REFERENCES learners(id) ON DELETE CASCADE,
  preferences   JSONB NOT NULL DEFAULT '{}', -- e.g. learning-experience preset, accessibility needs
  created_at    TIMESTAMPTZ NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL
);


-- ============================================================
-- 3. QUESTION BANK / ASSESSMENT CATALOG
--    (source: js/question-bank.js)
-- ============================================================

CREATE TABLE questions (
  id                TEXT PRIMARY KEY,       -- e.g. 'q_frac_001'
  subject           TEXT NOT NULL,
  chapter           TEXT NOT NULL,
  topic             TEXT NOT NULL,
  concept           TEXT NOT NULL,
  difficulty        TEXT NOT NULL,
  type              TEXT NOT NULL CHECK (type IN
                       ('mcq','true_false','short_answer','long_answer','math','step_based','written_response')),
  marks             NUMERIC NOT NULL,
  time_estimate_sec INTEGER,
  text              TEXT NOT NULL,
  options           JSONB,                  -- mcq/true_false option list
  correct_answer    TEXT,                   -- null for AI-graded-only questions without a single correct string
  model_answer      TEXT,
  explanation       TEXT,
  common_error_type TEXT,
  created_at        TIMESTAMPTZ NOT NULL,
  updated_at        TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_questions_concept ON questions(concept);
CREATE INDEX idx_questions_subject_chapter ON questions(subject, chapter);

CREATE TABLE assessments (
  id            TEXT PRIMARY KEY,           -- e.g. 'a_quick_fractions_quiz'
  title         TEXT NOT NULL,
  subject       TEXT,
  chapter       TEXT,
  total_marks   NUMERIC NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE assessment_questions (
  assessment_id TEXT NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
  question_id   TEXT NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
  position      INTEGER NOT NULL,
  PRIMARY KEY (assessment_id, question_id)
);


-- ============================================================
-- 4. ASSESSMENT ATTEMPTS / ANSWERS / RESULTS
--    (source: js/baa-assessment.js — attempts/evidence/teacherReviews)
--    Every attempt is its own row. A new attempt NEVER overwrites
--    a prior one (attempt_number is a sequence, see SCHEMA.md §8).
-- ============================================================

CREATE TABLE assessment_attempts (
  id                TEXT PRIMARY KEY,       -- e.g. 'attempt_...'
  assessment_id     TEXT NOT NULL REFERENCES assessments(id) ON DELETE RESTRICT,
  learner_id        TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  attempt_number    INTEGER NOT NULL,       -- 1..n per (learner_id, assessment_id)
  start_time        TIMESTAMPTZ NOT NULL,
  end_time          TIMESTAMPTZ,
  status            TEXT NOT NULL DEFAULT 'in_progress'
                       CHECK (status IN ('in_progress','submitted','evaluated')),
  evaluation_status TEXT NOT NULL DEFAULT 'pending'
                       CHECK (evaluation_status IN ('pending','partial','complete','failed')),
  review_status     TEXT NOT NULL DEFAULT 'not_reviewed'
                       CHECK (review_status IN ('not_reviewed','pending_review','accepted','edited','rejected')),
  score             NUMERIC,
  max_score         NUMERIC,
  UNIQUE (learner_id, assessment_id, attempt_number)
);
CREATE INDEX idx_attempts_learner ON assessment_attempts(learner_id);
CREATE INDEX idx_attempts_assessment ON assessment_attempts(assessment_id);

-- Raw submitted answers, one per question per attempt (source data).
CREATE TABLE assessment_answers (
  id            TEXT PRIMARY KEY,
  attempt_id    TEXT NOT NULL REFERENCES assessment_attempts(id) ON DELETE CASCADE,
  question_id   TEXT NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
  raw_answer    TEXT,
  answered_at   TIMESTAMPTZ NOT NULL,
  UNIQUE (attempt_id, question_id)
);

-- Graded result per question per attempt (source data — this is the
-- durable record of what grade a question received and how).
CREATE TABLE assessment_results (
  id                    TEXT PRIMARY KEY,
  attempt_id            TEXT NOT NULL REFERENCES assessment_attempts(id) ON DELETE CASCADE,
  question_id           TEXT NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
  grading_mode          TEXT NOT NULL CHECK (grading_mode IN ('auto','ai')),
  is_correct            BOOLEAN,           -- auto-graded only; null for AI-graded (see correctness)
  correctness            TEXT,              -- 'correct'|'incorrect'|'partially_correct'|'uncertain'
  score                 NUMERIC,           -- null = evaluation failed, never fabricated
  max_score             NUMERIC NOT NULL,
  confidence            TEXT,              -- 'high'|'medium'|'low'|'human_review_required'
  human_review_required BOOLEAN NOT NULL DEFAULT FALSE,
  evaluation_failed      BOOLEAN NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL,
  UNIQUE (attempt_id, question_id)
);
CREATE INDEX idx_results_attempt ON assessment_results(attempt_id);

-- AI evaluation is stored as its own record, separate from the teacher's
-- eventual decision (SCHEMA.md §13 / requirement 13: "AI evaluation is
-- not the teacher decision"). One row per AI grading call.
CREATE TABLE ai_evaluation_records (
  id                   TEXT PRIMARY KEY,
  attempt_id           TEXT NOT NULL REFERENCES assessment_attempts(id) ON DELETE CASCADE,
  question_id          TEXT NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
  model                TEXT,               -- e.g. 'gemini-3.5-flash-lite'
  score                NUMERIC,
  correctness           TEXT,
  explanation           TEXT,
  errors                JSONB,              -- array of tagged error strings
  missing_concepts       JSONB,
  suggested_improvement  TEXT,
  confidence            TEXT,
  human_review_required BOOLEAN NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_ai_eval_attempt ON ai_evaluation_records(attempt_id);

-- Human review queue + decision. References the AI evaluation it is
-- reviewing but is its own row — accepting/editing/rejecting never
-- overwrites the AI evaluation record above.
CREATE TABLE teacher_reviews (
  id                    TEXT PRIMARY KEY,
  attempt_id            TEXT NOT NULL REFERENCES assessment_attempts(id) ON DELETE CASCADE,
  question_id           TEXT NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
  ai_evaluation_id      TEXT REFERENCES ai_evaluation_records(id) ON DELETE SET NULL,
  learner_id            TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  teacher_status        TEXT NOT NULL DEFAULT 'pending'
                           CHECK (teacher_status IN ('pending','accepted','edited','rejected')),
  teacher_marks         NUMERIC,
  teacher_comment        TEXT,
  reviewer_user_id       TEXT REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_reviews_learner ON teacher_reviews(learner_id);
CREATE INDEX idx_reviews_status ON teacher_reviews(teacher_status);

-- Free-text teacher notes (source: teacher-os.html Section D notes store).
CREATE TABLE teacher_notes (
  id            TEXT PRIMARY KEY,
  learner_id    TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  author_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  text          TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_teacher_notes_learner ON teacher_notes(learner_id);


-- ============================================================
-- 5. LEARNING EVIDENCE / LEARNING MEMORY / MISTAKE PATTERNS
--    Evidence is SOURCE data. learning_memory is DERIVED/cacheable
--    (see SCHEMA.md §10) — it can always be recomputed from evidence.
-- ============================================================

CREATE TABLE learning_evidence (
  id            TEXT PRIMARY KEY,           -- e.g. 'ev_...'
  learner_id    TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  attempt_id    TEXT NOT NULL REFERENCES assessment_attempts(id) ON DELETE CASCADE,
  assessment_id TEXT NOT NULL REFERENCES assessments(id) ON DELETE RESTRICT,
  question_id   TEXT NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
  subject       TEXT NOT NULL,
  chapter       TEXT,
  topic         TEXT,
  concept       TEXT NOT NULL,
  difficulty    TEXT,
  correctness   TEXT NOT NULL,              -- 'correct'|'incorrect'|'partially_correct'|'uncertain'
  error_type    TEXT,
  score         NUMERIC,
  max_score     NUMERIC,
  confidence    TEXT,
  evidence_type TEXT NOT NULL DEFAULT 'assessment_answer', -- extensible: future evidence sources
  source        TEXT NOT NULL DEFAULT 'section_b_assessment',
  created_at    TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_evidence_learner ON learning_evidence(learner_id);
CREATE INDEX idx_evidence_learner_concept ON learning_evidence(learner_id, concept);
CREATE INDEX idx_evidence_attempt ON learning_evidence(attempt_id);

-- DERIVED. One row per (learner, concept). Recomputable from
-- learning_evidence at any time — see js/baa-assessment.js
-- updateLearningMemory() for the exact derivation rule being mirrored.
CREATE TABLE learning_memory (
  learner_id      TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  concept         TEXT NOT NULL,
  subject         TEXT,
  topic           TEXT,
  status          TEXT NOT NULL CHECK (status IN
                     ('insufficient_evidence','mastered','learning','needs_revision')),
  evidence_count  INTEGER NOT NULL DEFAULT 0,
  correct_count   INTEGER NOT NULL DEFAULT 0,
  last_updated    TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (learner_id, concept)
);

-- Append-only history of learning_memory transitions (bounded/rolled up
-- by the application layer, mirrors the in-memory `history` array today).
CREATE TABLE learning_memory_history (
  id            TEXT PRIMARY KEY,
  learner_id    TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  concept       TEXT NOT NULL,
  status        TEXT NOT NULL,
  evidence_count INTEGER NOT NULL,
  recorded_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_memory_history_learner_concept ON learning_memory_history(learner_id, concept);

-- Mistake patterns are DERIVED but must stay explainable (requirement
-- 12), so every pattern links back to the individual evidence rows that
-- produced it via mistake_pattern_occurrences rather than only storing
-- an aggregate count.
CREATE TABLE mistake_patterns (
  id             TEXT PRIMARY KEY,          -- e.g. 'pattern_...'
  learner_id     TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  concept        TEXT NOT NULL,
  subject        TEXT,
  error_type     TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'watching' CHECK (status IN ('watching','possible_misconception')),
  first_detected TIMESTAMPTZ NOT NULL,
  last_detected  TIMESTAMPTZ NOT NULL,
  UNIQUE (learner_id, concept, error_type)
);
CREATE INDEX idx_mistake_patterns_learner ON mistake_patterns(learner_id);

CREATE TABLE mistake_pattern_occurrences (
  id            TEXT PRIMARY KEY,
  pattern_id    TEXT NOT NULL REFERENCES mistake_patterns(id) ON DELETE CASCADE,
  evidence_id   TEXT NOT NULL REFERENCES learning_evidence(id) ON DELETE CASCADE,
  occurred_at   TIMESTAMPTZ NOT NULL,
  UNIQUE (pattern_id, evidence_id)
);
CREATE INDEX idx_pattern_occurrences_pattern ON mistake_pattern_occurrences(pattern_id);


-- ============================================================
-- 6. PLANNER
--    (source: js/baa-planner.js)
-- ============================================================

CREATE TABLE planner_preferences (
  learner_id                TEXT PRIMARY KEY REFERENCES learners(id) ON DELETE CASCADE,
  available_minutes_per_day INTEGER NOT NULL DEFAULT 30,
  updated_at                TIMESTAMPTZ NOT NULL
);

CREATE TABLE planner_goals (
  id            TEXT PRIMARY KEY,
  learner_id    TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  text          TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_planner_goals_learner ON planner_goals(learner_id);

CREATE TABLE planner_upcoming_assessments (
  id            TEXT PRIMARY KEY,
  learner_id    TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  subject       TEXT,
  date          DATE NOT NULL,
  assessment_id TEXT REFERENCES assessments(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_planner_upcoming_learner ON planner_upcoming_assessments(learner_id);

-- Tasks are never deleted on completion/miss — status transitions,
-- history preserved via planner_task_events (requirement 18/26).
CREATE TABLE planner_tasks (
  id                TEXT PRIMARY KEY,       -- e.g. 'task_...'
  learner_id        TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  type              TEXT NOT NULL,          -- e.g. 'practice' | 'revision' | 'reassessment'
  title             TEXT NOT NULL,
  concept           TEXT,
  subject           TEXT,
  estimated_minutes INTEGER NOT NULL,
  priority          TEXT NOT NULL,
  reasons           JSONB NOT NULL DEFAULT '[]', -- explainability: why this task was generated
  action            JSONB,                  -- e.g. { kind: 'assessment', assessmentId: ... }
  status            TEXT NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','completed','missed','cancelled','skipped')),
  scheduled_date    DATE NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL,
  completed_at      TIMESTAMPTZ
);
CREATE INDEX idx_planner_tasks_learner ON planner_tasks(learner_id);
CREATE INDEX idx_planner_tasks_learner_date ON planner_tasks(learner_id, scheduled_date);

CREATE TABLE planner_task_events (
  id            TEXT PRIMARY KEY,
  task_id       TEXT NOT NULL REFERENCES planner_tasks(id) ON DELETE CASCADE,
  event         TEXT NOT NULL,              -- 'created' | 'missed' | 'cancelled' | 'completed' | ...
  note          TEXT,
  occurred_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_planner_task_events_task ON planner_task_events(task_id);


-- ============================================================
-- 7. CONSENT / PREFERENCE + AUDIT FOUNDATIONS
--    Foundations only — no consent flow or audit trail is wired up
--    by G1. These exist so G2/G3/G6 have a place to write to.
-- ============================================================

CREATE TABLE consent_preferences (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  consent_type  TEXT NOT NULL,              -- e.g. 'data_processing' | 'ai_evaluation' | 'notifications'
  granted       BOOLEAN NOT NULL,
  granted_at    TIMESTAMPTZ NOT NULL,
  UNIQUE (user_id, consent_type)
);

CREATE TABLE audit_log (
  id            TEXT PRIMARY KEY,
  actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  action        TEXT NOT NULL,              -- e.g. 'teacher_review.decide', 'learner.deactivate'
  entity_type   TEXT NOT NULL,
  entity_id     TEXT NOT NULL,
  metadata      JSONB,
  created_at    TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_audit_entity ON audit_log(entity_type, entity_id);
CREATE INDEX idx_audit_actor ON audit_log(actor_user_id);

-- ============================================================
-- MODULE 51 — CHALLENGE & COMPETITION ARENA
-- Production persistence for cross-grade student challenges.
-- ============================================================
CREATE TABLE IF NOT EXISTS challenge_matches (
  id TEXT PRIMARY KEY,
  challenger_learner_id TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  challenged_learner_id TEXT NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
  mode TEXT NOT NULL CHECK (mode IN ('xp_race','quiz_battle','streak_battle','weekly_xp','team_battle')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','declined','completed','cancelled')),
  target_xp INTEGER NOT NULL DEFAULT 500 CHECK (target_xp >= 0),
  challenger_score NUMERIC NOT NULL DEFAULT 0,
  challenged_score NUMERIC NOT NULL DEFAULT 0,
  winner_learner_id TEXT REFERENCES learners(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  accepted_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  CHECK (challenger_learner_id <> challenged_learner_id)
);
