// api/ai-mode.js
// BAA OS — M1 AI Mode server planning contract.
export const config = { runtime: 'nodejs' };
import { requireAuth } from './_lib/auth.js';
import { consumeAiRateLimit } from './_lib/ai-rate-limit.js';
const MODEL='gemini-3.5-flash-lite';
const GEMINI_API_URL=`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`;
const MAX_GOAL_CHARS=120,MAX_CONCEPTS=20,MAX_STEPS=7,MAX_PREVIOUS_STEPS=7,MAX_OUTPUT_TOKENS=1400;
const MAX_REQUEST_BODY_BYTES=32*1024,REQUEST_TIMEOUT_MS=30000,MAX_RETRIES=2;
const VALID_CONFIDENCE=new Set(['high','medium','low','insufficient_evidence']);
const VALID_STATE=new Set(['mastered','strong','learning','needs_revision','struggling','insufficient_evidence']);
function corsHeaders(req){return {'Access-Control-Allow-Origin':process.env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin'};}
function jsonResponse(req,status,body){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...corsHeaders(req)}});}
function jsonError(req,status,code,message){return jsonResponse(req,status,{ok:false,error:{code,message}});}
function getClientIp(req){const fwd=req.headers.get('x-forwarded-for');if(fwd)return fwd.split(',')[0].trim();return req.headers.get('x-real-ip')||'unknown';}
async function readJsonBounded(req){const declared=Number(req.headers.get('content-length'));if(Number.isFinite(declared)&&declared>MAX_REQUEST_BODY_BYTES){try{await req.body?.cancel?.();}catch(_){}return {ok:false,error:'REQUEST_BODY_TOO_LARGE'};}if(!req.body||typeof req.body.getReader!=='function'){try{return {ok:true,body:await req.json()};}catch(_){return {ok:false,error:'INVALID_JSON'};}}const reader=req.body.getReader(),chunks=[];let total=0;try{while(true){const part=await reader.read();if(part.done)break;const chunk=part.value instanceof Uint8Array?part.value:new Uint8Array(part.value||[]);total+=chunk.byteLength;if(total>MAX_REQUEST_BODY_BYTES){try{await reader.cancel();}catch(_){}return {ok:false,error:'REQUEST_BODY_TOO_LARGE'};}chunks.push(chunk);}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}try{return {ok:true,body:JSON.parse(new TextDecoder().decode(bytes))};}catch(_){return {ok:false,error:'INVALID_JSON'};}}catch(_){try{await reader.cancel();}catch(_){}return {ok:false,error:'INVALID_JSON'};}}
function cleanText(value,max){if(typeof value!=='string')return '';return value.replace(/\s+/g,' ').trim().slice(0,max);}
export function validateBody(body){if(!body||typeof body!=='object')return {error:{code:'INVALID_BODY',message:'Request body must be an object.'}};const goal=cleanText(body.goal,MAX_GOAL_CHARS);if(!goal)return {error:{code:'GOAL_REQUIRED',message:'A learning goal is required.'}};if(!Array.isArray(body.concepts)||body.concepts.length>MAX_CONCEPTS)return {error:{code:'INVALID_CONCEPTS',message:`concepts must be an array of at most ${MAX_CONCEPTS} items.`}};const concepts=body.concepts.map(c=>{if(!c||typeof c!=='object')return null;const concept=cleanText(c.concept,80),state=cleanText(c.state,30),confidence=cleanText(c.confidence,30),evidenceCount=Number(c.evidenceCount);if(!concept||!VALID_STATE.has(state)||!VALID_CONFIDENCE.has(confidence)||!Number.isInteger(evidenceCount)||evidenceCount<0||evidenceCount>1000)return null;return {concept,state,confidence,evidenceCount};});if(concepts.some(c=>c===null))return {error:{code:'INVALID_CONCEPT',message:'Each concept needs valid concept, state, confidence and evidenceCount values.'}};const minutes=Number(body.availableMinutesPerDay);if(!Number.isFinite(minutes)||minutes<5||minutes>180)return {error:{code:'INVALID_TIME',message:'availableMinutesPerDay must be between 5 and 180.'}};const upcoming=Array.isArray(body.upcomingAssessments)?body.upcomingAssessments.slice(0,8).map(a=>({title:cleanText(a?.title,120),subject:cleanText(a?.subject,60)||null,date:cleanText(a?.date,10)})).filter(a=>a.title&&/^\d{4}-\d{2}-\d{2}$/.test(a.date)):[];const previousPlan=validatePreviousPlan(body.previousPlan);if(body.previousPlan!=null&&!previousPlan)return {error:{code:'INVALID_PREVIOUS_PLAN',message:'previousPlan is not a valid AI Mode plan.'}};return {goal,concepts,availableMinutesPerDay:Math.round(minutes),upcomingAssessments:upcoming,previousPlan};}
function validatePreviousPlan(value){if(value==null||!value||typeof value!=='object')return null;if(value.schemaVersion!==1||value.mode!=='ai'||!Array.isArray(value.steps)||value.steps.length<1||value.steps.length>MAX_PREVIOUS_STEPS)return null;const steps=value.steps.map(s=>({title:cleanText(s?.title,120),minutes:Number(s?.minutes),type:cleanText(s?.type,20)}));if(steps.some(s=>!s.title||!Number.isInteger(s.minutes)||s.minutes<5||s.minutes>120||!['learn','practice','review','assessment','tutor'].includes(s.type)))return null;return {summary:cleanText(value.summary,240),steps,totalMinutes:Number(value.totalMinutes)||steps.reduce((sum,s)=>sum+s.minutes,0)};}
function buildPrompt(input){const evidence=input.concepts.length?input.concepts.map(c=>`- ${c.concept}: state=${c.state}, confidence=${c.confidence}, evidenceCount=${c.evidenceCount}`).join('\n'):'- No concept evidence is available yet.';const assessments=input.upcomingAssessments.length?input.upcomingAssessments.map(a=>`- ${a.title}${a.subject?` (${a.subject})`:''} on ${a.date}`).join('\n'):'- No upcoming assessments supplied.';return `You are BAA's AI Mode planner. Create a short, actionable academic path using ONLY the learner evidence and goal supplied below.\n\nGOAL:\n${input.goal}\n\nREAL LEARNING EVIDENCE:\n${evidence}\n\nAVAILABLE DAILY TIME:\n${input.availableMinutesPerDay} minutes\n\nUPCOMING ASSESSMENTS:\n${assessments}\n\nPREVIOUS AI MODE PLAN (if adapting):\n${input.previousPlan?JSON.stringify(input.previousPlan):'No previous plan supplied. Create the first plan.'}\n\nReturn ONLY JSON with schemaVersion 1, mode ai, summary, and 1-${MAX_STEPS} steps. Each step needs title, minutes, type (learn|practice|review|assessment|tutor), and evidence-backed reason. Total minutes must not exceed the learner's daily time. Prioritize struggling/needs_revision concepts. If evidence is insufficient, say so and do not claim mastery. Do not invent grades, history, strengths, weaknesses, medical, psychological, or disciplinary claims.`;}
async function callGemini(payload,apiKey,attempt=0){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const res=await fetch(`${GEMINI_API_URL}?key=${apiKey}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});clearTimeout(timeout);if(!res.ok&&res.status>=500&&attempt<MAX_RETRIES){await new Promise(r=>setTimeout(r,400*(attempt+1)));return callGemini(payload,apiKey,attempt+1);}return res;}catch(err){clearTimeout(timeout);if(attempt<MAX_RETRIES){await new Promise(r=>setTimeout(r,400*(attempt+1)));return callGemini(payload,apiKey,attempt+1);}throw new Error(err?.name==='AbortError'?'upstream timeout':'upstream network error');}}
function extractJson(text){const cleaned=String(text||'').replace(/```json/gi,'').replace(/```/g,'').trim(),start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start<0||end<=start)return null;try{return JSON.parse(cleaned.slice(start,end+1));}catch{return null;}}
export function normalizePlan(raw,input){if(!raw||typeof raw!=='object'||raw.schemaVersion!==1||raw.mode!=='ai')return {error:{code:'INVALID_AI_PLAN',message:'AI returned an invalid plan schema.'}};if(!Array.isArray(raw.steps)||raw.steps.length<1||raw.steps.length>MAX_STEPS)return {error:{code:'INVALID_AI_PLAN',message:'AI returned an invalid step list.'}};const allowed=new Set(['learn','practice','review','assessment','tutor']);let total=0;const steps=[];for(const step of raw.steps){const title=cleanText(step?.title,120),reason=cleanText(step?.reason,240),minutes=Number(step?.minutes),type=cleanText(step?.type,20);if(!title||!reason||!allowed.has(type)||!Number.isInteger(minutes)||minutes<5||minutes>120)return {error:{code:'INVALID_AI_STEP',message:'AI returned an invalid plan step.'}};total+=minutes;steps.push({title,minutes,type,reason});}if(total>input.availableMinutesPerDay)return {error:{code:'PLAN_EXCEEDS_TIME',message:'AI plan exceeds the learner time budget.'}};return {plan:{schemaVersion:1,mode:'ai',summary:cleanText(raw.summary,240)||'Your AI Mode learning path is ready.',steps,totalMinutes:total,generatedAt:new Date().toISOString(),evidenceBound:true,adaptedFromPreviousPlan:Boolean(input.previousPlan)}};}
export default async function handler(req){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(req)});if(req.method!=='POST')return jsonError(req,405,'METHOD_NOT_ALLOWED','Method not allowed.');const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return jsonError(req,503,'AI_CONFIGURATION_MISSING','AI Mode is not configured on the server yet.');let session;try{session=await requireAuth(req);}catch(e){return jsonError(req,e.status||401,'AUTH_REQUIRED',e.message||'Authentication required.');}let rate;try{rate=await consumeAiRateLimit('ai-mode',session.user_id||getClientIp(req),{windowSeconds:300,maxRequests:12});}catch{return jsonError(req,503,'RATE_LIMIT_UNAVAILABLE','AI rate-limit service is temporarily unavailable.');}if(rate.limited)return jsonError(req,429,'RATE_LIMITED','Too many AI Mode requests. Please wait a moment.');const parsed=await readJsonBounded(req);if(!parsed.ok)return jsonError(req,400,parsed.error,parsed.error==='REQUEST_BODY_TOO_LARGE'?'Request body is too large.':'Request body must be valid JSON.');const validated=validateBody(parsed.body);if(validated.error)return jsonError(req,400,validated.error.code,validated.error.message);const payload={contents:[{role:'user',parts:[{text:buildPrompt(validated)}]}],generationConfig:{maxOutputTokens:MAX_OUTPUT_TOKENS,responseMimeType:'application/json',thinkingConfig:{thinkingLevel:'low'}},safetySettings:[{category:'HARM_CATEGORY_DANGEROUS_CONTENT',threshold:'BLOCK_MEDIUM_AND_ABOVE'}]};let upstream;try{upstream=await callGemini(payload,apiKey);}catch{return jsonError(req,502,'AI_UPSTREAM_UNAVAILABLE','AI Mode is temporarily unavailable.');}if(!upstream.ok)return jsonError(req,upstream.status>=500?502:400,'AI_UPSTREAM_ERROR','AI Mode could not generate a plan right now.');let data;try{data=await upstream.json();}catch{return jsonError(req,502,'AI_INVALID_RESPONSE','AI Mode returned an unreadable response.');}const text=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'',normalized=normalizePlan(extractJson(text),validated);if(normalized.error)return jsonError(req,502,normalized.error.code,normalized.error.message);return jsonResponse(req,200,normalized.plan);}
