import { json, id, writeAudit } from './_lib/security.js';
import { requireAuth, hasRole } from './_lib/auth.js';
import { sql } from './_lib/db.js';
export const config={runtime:'nodejs'};
const clean=(v,n=500)=>String(v??'').trim().slice(0,n);
const PERMISSIONS=new Set(['read_learning','write_learning','read_calendar','read_assessment']);
const VERSION=/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/;
function noStore(res){res.setHeader('Cache-Control','private, no-store, max-age=0');}
function validHttps(url){return /^https:\/\/[^\s]+$/i.test(url);}
export default async function handler(req,res){noStore(res);try{const s=await requireAuth(req);if(req.method==='GET'){const rows=await sql`SELECT id,name,version,description,entry_url AS "entryUrl",permissions,enabled,created_at AS "createdAt",updated_at AS "updatedAt" FROM installed_plugins WHERE enabled=true ORDER BY name,version DESC`;return json(res,200,{ok:true,plugins:rows.rows.map(p=>({...p,permissions:Array.isArray(p.permissions)?p.permissions.filter(x=>PERMISSIONS.has(String(x))):[]}))});}if(req.method!=='POST'||!hasRole(s,'admin'))return json(res,403,{error:{code:'FORBIDDEN',message:'Administrator role required to install or change plugins.'}});const b=req.body||{},action=clean(b.action,40);if(action==='install'){const name=clean(b.name,120),version=clean(b.version,40),description=clean(b.description,1000),entryUrl=clean(b.entryUrl,1000);if(!name||!VERSION.test(version)||!validHttps(entryUrl))return json(res,400,{error:{code:'INVALID_PLUGIN',message:'name, semver version and an HTTPS entryUrl are required.'}});const permissions=Array.isArray(b.permissions)?[...new Set(b.permissions.map(x=>clean(x,80)))]:[];if(permissions.some(x=>!PERMISSIONS.has(x)))return json(res,400,{error:{code:'INVALID_PLUGIN_PERMISSION',message:'Plugin requests an unsupported permission.'}});const pluginId=id('plugin');const existing=await sql`SELECT id FROM installed_plugins WHERE name=${name} AND version=${version} LIMIT 1`;await sql`INSERT INTO installed_plugins(id,name,version,description,entry_url,permissions,enabled,created_by) VALUES(${pluginId},${name},${version},${description},${entryUrl},${JSON.stringify(permissions)}::jsonb,true,${s.user_id}) ON CONFLICT(name,version) DO UPDATE SET description=EXCLUDED.description,entry_url=EXCLUDED.entry_url,permissions=EXCLUDED.permissions,enabled=true,updated_at=NOW()`;const effectiveId=existing.rows[0]?.id||pluginId;await writeAudit({actorUserId:s.user_id,action:'plugin.install',entityType:'plugin',entityId:effectiveId,metadata:{name,version,permissionCount:permissions.length,permissions}});return json(res,201,{ok:true,id:effectiveId,name,version,permissions});}if(action==='toggle'){const pluginId=clean(b.id,120);if(!pluginId)return json(res,400,{error:{code:'INVALID_PLUGIN_ID',message:'Plugin id is required.'}});const enabled=Boolean(b.enabled);const updated=await sql`UPDATE installed_plugins SET enabled=${enabled},updated_at=NOW() WHERE id=${pluginId} RETURNING id`;if(!updated.rows.length)return json(res,404,{error:{code:'PLUGIN_NOT_FOUND',message:'Plugin not found.'}});await writeAudit({actorUserId:s.user_id,action:'plugin.toggle',entityType:'plugin',entityId:pluginId,metadata:{enabled}});return json(res,200,{ok:true,id:pluginId,enabled});}return json(res,400,{error:{code:'INVALID_ACTION',message:'Supported actions: install, toggle.'}});}catch(e){return json(res,e.status||500,{error:{code:e.code||'PLUGIN_FAILED',message:e.status?e.message:'Unable to process plugin request.'}})}}
